theme: jekyll-theme-minimal
title: Daoyuan Wang
logo: /image.JPG
description: >
  <span class="chinese-name">王道远</span>
  <span class="profile-role">Ph.D. Candidate<br>Central South University</span>
  <span class="profile-links">
    <a href="mailto:wdyi701@gmail.com">Email</a>
    <a href="https://scholar.google.com/citations?user=ZIwb6NwAAAAJ">Google Scholar</a>
    <a href="https://github.com/wdyi701">GitHub</a>
    <a href="https://orcid.org/0000-0001-8463-4104">ORCID</a>
  </span>
