theme: jekyll-theme-minimal
title: "<left>Daoyuan Wang <br> <span style='font-size: 0.8em;'>王道远</span></left>"
description: >
  Ph.D. Candidate @ CSU <br>
  <hr>
  <a href="mailto:wdyi701@gmail.com" style="text-decoration: none; color: #0366d6;">wdyi701@gmail.com</a>
  <br>
  <a href="https://scholar.google.com">Google Scholar</a> <br>
  <a href="https://github.com/wdyi701">GitHub</a> <br>
  <a href="https://orcid.org/0000-0001-8463-4104" target="_blank" style="text-decoration:none;">ORCID</a>
logo: /image.JPG
github: [owner/repo]
